export {default as ShowcaseBanner} from './Showcase';
export {default as Loader} from './Loader';
export {Loader2 as LoaderAlt} from './Loader';
export {default as AssetUploader} from './Upload';
export {default as FruitsSection} from './Sections/Fruits';
export {default as MenuSection} from './Sections/Menu';
export {default as EmptyCart} from './EmptyCart';
export {default as Cart} from './Cart';
export {default as Sidenav} from './Admin/Sidenav';
export {default as Content} from './Admin/Content';
export {default as AddFood} from './Admin/AddFood';
export { default as Stats } from './Admin/Dashboard';
import NavBar from "./layout/NavBar/NavBar";
import Footer from "./layout/Footer/Footer";
export { NavBar, Footer };